"""add OTX tables

Revision ID: 056dcdcb76d0
Revises: 48913e25c3df
Create Date: 2026-09-13 15:45:57.345626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '056dcdcb76d0'
down_revision: Union[str, Sequence[str], None] = '48913e25c3df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otx_observations',
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('pulse_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['source_observations.observation_id'], ),
    sa.PrimaryKeyConstraint('observation_id')
    )
    op.create_table('otx_pulses',
    sa.Column('pulse_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('author_name', sa.String(), nullable=False),
    sa.Column('tlp', sa.String(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('adversary', sa.String(), nullable=False),
    sa.Column('otx_observation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['otx_observation_id'], ['otx_observations.observation_id'], ),
    sa.PrimaryKeyConstraint('pulse_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('otx_pulses')
    op.drop_table('otx_observations')
    # ### end Alembic commands ###
