"""add AbuseIPDB tables

Revision ID: 48913e25c3df
Revises: dfa6e36470cd
Create Date: 2026-09-13 14:34:35.227437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48913e25c3df'
down_revision: Union[str, Sequence[str], None] = 'dfa6e36470cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abuseipdb_observations',
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('abuse_confidence_score', sa.Integer(), nullable=False),
    sa.Column('total_reports', sa.Integer(), nullable=False),
    sa.Column('num_distinct_users', sa.Integer(), nullable=False),
    sa.Column('last_reported_at', sa.DateTime(), nullable=False),
    sa.Column('is_whitelisted', sa.Boolean(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('country_name', sa.String(), nullable=False),
    sa.Column('usage_type', sa.String(), nullable=False),
    sa.Column('isp', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('is_tor', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['source_observations.observation_id'], ),
    sa.PrimaryKeyConstraint('observation_id')
    )
    op.create_table('abuse_reports',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reporter_country_code', sa.String(), nullable=False),
    sa.Column('reporter_country_name', sa.String(), nullable=False),
    sa.Column('abuseipdb_observation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['abuseipdb_observation_id'], ['abuseipdb_observations.observation_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('abuse_report_category',
    sa.Column('report_category_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['abuse_reports.report_id'], ),
    sa.PrimaryKeyConstraint('report_category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abuse_report_category')
    op.drop_table('abuse_reports')
    op.drop_table('abuseipdb_observations')
    # ### end Alembic commands ###
