"""update nullable constraints

Revision ID: 49c8e20a2c9a
Revises: 056dcdcb76d0
Create Date: 2026-09-13 16:31:21.073926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49c8e20a2c9a'
down_revision: Union[str, Sequence[str], None] = '056dcdcb76d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('abuse_reports', 'comment',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('abuse_reports', 'reporter_country_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('abuse_reports', 'reporter_country_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('abuseipdb_observations', 'last_reported_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('abuseipdb_observations', 'is_whitelisted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('abuseipdb_observations', 'country_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('abuseipdb_observations', 'country_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('abuseipdb_observations', 'usage_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('abuseipdb_observations', 'isp',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('abuseipdb_observations', 'domain',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('abuseipdb_observations', 'is_tor',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('otx_pulses', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('otx_pulses', 'tlp',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('otx_pulses', 'adversary',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('virus_total_analysis_results', 'engine_version',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('virus_total_analysis_results', 'method',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('virus_total_analysis_results', 'result',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('virus_total_observations', 'first_submission_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('virus_total_observations', 'last_submission_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('virus_total_observations', 'last_analysis_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('virus_total_observations', 'last_modification_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('virus_total_observations', 'last_modification_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('virus_total_observations', 'last_analysis_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('virus_total_observations', 'last_submission_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('virus_total_observations', 'first_submission_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('virus_total_analysis_results', 'result',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('virus_total_analysis_results', 'method',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('virus_total_analysis_results', 'engine_version',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('otx_pulses', 'adversary',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('otx_pulses', 'tlp',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('otx_pulses', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('abuseipdb_observations', 'is_tor',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('abuseipdb_observations', 'domain',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('abuseipdb_observations', 'isp',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('abuseipdb_observations', 'usage_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('abuseipdb_observations', 'country_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('abuseipdb_observations', 'country_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('abuseipdb_observations', 'is_whitelisted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('abuseipdb_observations', 'last_reported_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('abuse_reports', 'reporter_country_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('abuse_reports', 'reporter_country_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('abuse_reports', 'comment',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
