"""add source observations and virus total

Revision ID: dfa6e36470cd
Revises: 636386fd9edc
Create Date: 2026-09-12 14:38:54.904261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa6e36470cd'
down_revision: Union[str, Sequence[str], None] = '636386fd9edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('source_observations',
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('ioc_id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['ioc_id'], ['iocs.ioc_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.source_id'], ),
    sa.PrimaryKeyConstraint('observation_id')
    )
    op.create_table('virus_total_observations',
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('first_submission_date', sa.DateTime(), nullable=False),
    sa.Column('last_submission_date', sa.DateTime(), nullable=False),
    sa.Column('last_analysis_date', sa.DateTime(), nullable=False),
    sa.Column('last_modification_date', sa.DateTime(), nullable=False),
    sa.Column('times_submitted', sa.Integer(), nullable=False),
    sa.Column('reputation', sa.Integer(), nullable=False),
    sa.Column('malicious_count', sa.Integer(), nullable=False),
    sa.Column('suspicious_count', sa.Integer(), nullable=False),
    sa.Column('harmless_count', sa.Integer(), nullable=False),
    sa.Column('undetected_count', sa.Integer(), nullable=False),
    sa.Column('timeout_count', sa.Integer(), nullable=False),
    sa.Column('votes_harmless', sa.Integer(), nullable=False),
    sa.Column('votes_malicious', sa.Integer(), nullable=False),
    sa.Column('unique_sources', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['source_observations.observation_id'], ),
    sa.PrimaryKeyConstraint('observation_id')
    )
    op.create_table('virus_total_analysis_results',
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('engine_name', sa.String(), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['virus_total_observations.observation_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('virus_total_analysis_results')
    op.drop_table('virus_total_observations')
    op.drop_table('source_observations')
    op.drop_table('source')
    # ### end Alembic commands ###
